"""Pre-prepared actor descriptions for the protocol, for when autodiscovery fails."""

actor_descriptions = {u'from': u'root',
 u'types': {u'appliedStylesReturn': {u'category': u'dict',
                                     u'specializations': {u'entries': u'array:appliedstyle',
                                                          u'rules': u'array:domstylerule',
                                                          u'sheets': u'array:stylesheet'},
                                     u'typeName': u'appliedStylesReturn'},
            u'appliedstyle': {u'category': u'dict',
                              u'specializations': {u'inherited': u'nullable:domnode#actorid',
                                                   u'rule': u'domstylerule#actorid'},
                              u'typeName': u'appliedstyle'},
            u'device': {u'category': u'actor',
                        u'methods': [{u'name': u'getDescription',
                                      u'request': {u'type': u'getDescription'},
                                      u'response': {u'value': {u'_retval': u'json'}}},
                                     {u'name': u'getWallpaper',
                                      u'request': {u'type': u'getWallpaper'},
                                      u'response': {u'value': {u'_retval': u'longstring'}}},
                                     {u'name': u'screenshotToDataURL',
                                      u'request': {u'type': u'screenshotToDataURL'},
                                      u'response': {u'value': {u'_retval': u'longstring'}}},
                                     {u'name': u'getRawPermissionsTable',
                                      u'request': {u'type': u'getRawPermissionsTable'},
                                      u'response': {u'value': {u'_retval': u'json'}}}],
                        u'typeName': u'device'},
            u'disconnectedNode': {u'category': u'dict',
                                  u'specializations': {u'newParents': u'array:domnode',
                                                       u'node': u'domnode'},
                                  u'typeName': u'disconnectedNode'},
            u'disconnectedNodeArray': {u'category': u'dict',
                                       u'specializations': {u'newParents': u'array:domnode',
                                                            u'nodes': u'array:domnode'},
                                       u'typeName': u'disconnectedNodeArray'},
            u'dommutation': {u'category': u'dict',
                             u'specializations': {},
                             u'typeName': u'dommutation'},
            u'domnode': {u'category': u'actor',
                         u'methods': [{u'name': u'getNodeValue',
                                       u'request': {u'type': u'getNodeValue'},
                                       u'response': {u'value': {u'_retval': u'longstring'}}},
                                      {u'name': u'setNodeValue',
                                       u'request': {u'type': u'setNodeValue',
                                                    u'value': {u'_arg': 0,
                                                               u'type': u'primitive'}},
                                       u'response': {}},
                                      {u'name': u'getImageData',
                                       u'request': {u'maxDim': {u'_arg': 0,
                                                                u'type': u'nullable:number'},
                                                    u'type': u'getImageData'},
                                       u'response': {u'_retval': u'imageData'}},
                                      {u'name': u'modifyAttributes',
                                       u'request': {u'modifications': {u'_arg': 0,
                                                                       u'type': u'array:json'},
                                                    u'type': u'modifyAttributes'},
                                       u'response': {}}],
                         u'typeName': u'domnode'},
            u'domnodelist': {u'category': u'actor',
                             u'methods': [{u'name': u'item',
                                           u'request': {u'item': {u'_arg': 0,
                                                                  u'type': u'primitive'},
                                                        u'type': u'item'},
                                           u'response': {u'_retval': u'disconnectedNode'}},
                                          {u'name': u'items',
                                           u'request': {u'end': {u'_arg': 1,
                                                                 u'type': u'nullable:number'},
                                                        u'start': {u'_arg': 0,
                                                                   u'type': u'nullable:number'},
                                                        u'type': u'items'},
                                           u'response': {u'_retval': u'disconnectedNodeArray'}},
                                          {u'name': u'release',
                                           u'release': True,
                                           u'request': {u'type': u'release'},
                                           u'response': {}}],
                             u'typeName': u'domnodelist'},
            u'domstylerule': {u'category': u'actor',
                              u'methods': [{u'name': u'modifyProperties',
                                            u'request': {u'modifications': {u'_arg': 0,
                                                                            u'type': u'array:json'},
                                                         u'type': u'modifyProperties'},
                                            u'response': {u'rule': {u'_retval': u'domstylerule'}}}],
                              u'typeName': u'domstylerule'},
            u'domtraversalarray': {u'category': u'dict',
                                   u'specializations': {u'nodes': u'array:domnode'},
                                   u'typeName': u'domtraversalarray'},
            u'domwalker': {u'category': u'actor',
                           u'methods': [{u'name': u'release',
                                         u'release': True,
                                         u'request': {u'type': u'release'},
                                         u'response': {}},
                                        {u'name': u'pick',
                                         u'request': {u'type': u'pick'},
                                         u'response': {u'_retval': u'disconnectedNode'}},
                                        {u'name': u'cancelPick',
                                         u'request': {u'type': u'cancelPick'},
                                         u'response': {}},
                                        {u'name': u'highlight',
                                         u'request': {u'node': {u'_arg': 0,
                                                                u'type': u'nullable:domnode'},
                                                      u'type': u'highlight'},
                                         u'response': {}},
                                        {u'name': u'document',
                                         u'request': {u'node': {u'_arg': 0,
                                                                u'type': u'nullable:domnode'},
                                                      u'type': u'document'},
                                         u'response': {u'node': {u'_retval': u'domnode'}}},
                                        {u'name': u'documentElement',
                                         u'request': {u'node': {u'_arg': 0,
                                                                u'type': u'nullable:domnode'},
                                                      u'type': u'documentElement'},
                                         u'response': {u'node': {u'_retval': u'domnode'}}},
                                        {u'name': u'parents',
                                         u'request': {u'node': {u'_arg': 0,
                                                                u'type': u'domnode'},
                                                      u'sameDocument': {u'_option': 1,
                                                                        u'type': u'primitive'},
                                                      u'type': u'parents'},
                                         u'response': {u'nodes': {u'_retval': u'array:domnode'}}},
                                        {u'name': u'retainNode',
                                         u'request': {u'node': {u'_arg': 0,
                                                                u'type': u'domnode'},
                                                      u'type': u'retainNode'},
                                         u'response': {}},
                                        {u'name': u'unretainNode',
                                         u'request': {u'node': {u'_arg': 0,
                                                                u'type': u'domnode'},
                                                      u'type': u'unretainNode'},
                                         u'response': {}},
                                        {u'name': u'releaseNode',
                                         u'request': {u'force': {u'_option': 1,
                                                                 u'type': u'primitive'},
                                                      u'node': {u'_arg': 0,
                                                                u'type': u'domnode'},
                                                      u'type': u'releaseNode'},
                                         u'response': {}},
                                        {u'name': u'children',
                                         u'request': {u'center': {u'_option': 1,
                                                                  u'type': u'domnode'},
                                                      u'maxNodes': {u'_option': 1,
                                                                    u'type': u'primitive'},
                                                      u'node': {u'_arg': 0,
                                                                u'type': u'domnode'},
                                                      u'start': {u'_option': 1,
                                                                 u'type': u'domnode'},
                                                      u'type': u'children',
                                                      u'whatToShow': {u'_option': 1,
                                                                      u'type': u'primitive'}},
                                         u'response': {u'_retval': u'domtraversalarray'}},
                                        {u'name': u'siblings',
                                         u'request': {u'center': {u'_option': 1,
                                                                  u'type': u'domnode'},
                                                      u'maxNodes': {u'_option': 1,
                                                                    u'type': u'primitive'},
                                                      u'node': {u'_arg': 0,
                                                                u'type': u'domnode'},
                                                      u'start': {u'_option': 1,
                                                                 u'type': u'domnode'},
                                                      u'type': u'siblings',
                                                      u'whatToShow': {u'_option': 1,
                                                                      u'type': u'primitive'}},
                                         u'response': {u'_retval': u'domtraversalarray'}},
                                        {u'name': u'nextSibling',
                                         u'request': {u'node': {u'_arg': 0,
                                                                u'type': u'domnode'},
                                                      u'type': u'nextSibling',
                                                      u'whatToShow': {u'_option': 1,
                                                                      u'type': u'primitive'}},
                                         u'response': {u'node': {u'_retval': u'nullable:domnode'}}},
                                        {u'name': u'previousSibling',
                                         u'request': {u'node': {u'_arg': 0,
                                                                u'type': u'domnode'},
                                                      u'type': u'previousSibling',
                                                      u'whatToShow': {u'_option': 1,
                                                                      u'type': u'primitive'}},
                                         u'response': {u'node': {u'_retval': u'nullable:domnode'}}},
                                        {u'name': u'querySelector',
                                         u'request': {u'node': {u'_arg': 0,
                                                                u'type': u'domnode'},
                                                      u'selector': {u'_arg': 1,
                                                                    u'type': u'primitive'},
                                                      u'type': u'querySelector'},
                                         u'response': {u'_retval': u'disconnectedNode'}},
                                        {u'name': u'querySelectorAll',
                                         u'request': {u'node': {u'_arg': 0,
                                                                u'type': u'domnode'},
                                                      u'selector': {u'_arg': 1,
                                                                    u'type': u'primitive'},
                                                      u'type': u'querySelectorAll'},
                                         u'response': {u'list': {u'_retval': u'domnodelist'}}},
                                        {u'name': u'getSuggestionsForQuery',
                                         u'request': {u'completing': {u'_arg': 1,
                                                                      u'type': u'primitive'},
                                                      u'query': {u'_arg': 0,
                                                                 u'type': u'primitive'},
                                                      u'selectorState': {u'_arg': 2,
                                                                         u'type': u'primitive'},
                                                      u'type': u'getSuggestionsForQuery'},
                                         u'response': {u'list': {u'_retval': u'array:array:string'}}},
                                        {u'name': u'addPseudoClassLock',
                                         u'request': {u'node': {u'_arg': 0,
                                                                u'type': u'domnode'},
                                                      u'parents': {u'_option': 2,
                                                                   u'type': u'primitive'},
                                                      u'pseudoClass': {u'_arg': 1,
                                                                       u'type': u'primitive'},
                                                      u'type': u'addPseudoClassLock'},
                                         u'response': {}},
                                        {u'name': u'hideNode',
                                         u'request': {u'node': {u'_arg': 0,
                                                                u'type': u'domnode'},
                                                      u'type': u'hideNode'},
                                         u'response': {}},
                                        {u'name': u'unhideNode',
                                         u'request': {u'node': {u'_arg': 0,
                                                                u'type': u'domnode'},
                                                      u'type': u'unhideNode'},
                                         u'response': {}},
                                        {u'name': u'removePseudoClassLock',
                                         u'request': {u'node': {u'_arg': 0,
                                                                u'type': u'domnode'},
                                                      u'parents': {u'_option': 2,
                                                                   u'type': u'primitive'},
                                                      u'pseudoClass': {u'_arg': 1,
                                                                       u'type': u'primitive'},
                                                      u'type': u'removePseudoClassLock'},
                                         u'response': {}},
                                        {u'name': u'clearPseudoClassLocks',
                                         u'request': {u'node': {u'_arg': 0,
                                                                u'type': u'nullable:domnode'},
                                                      u'type': u'clearPseudoClassLocks'},
                                         u'response': {}},
                                        {u'name': u'innerHTML',
                                         u'request': {u'node': {u'_arg': 0,
                                                                u'type': u'domnode'},
                                                      u'type': u'innerHTML'},
                                         u'response': {u'value': {u'_retval': u'longstring'}}},
                                        {u'name': u'outerHTML',
                                         u'request': {u'node': {u'_arg': 0,
                                                                u'type': u'domnode'},
                                                      u'type': u'outerHTML'},
                                         u'response': {u'value': {u'_retval': u'longstring'}}},
                                        {u'name': u'setOuterHTML',
                                         u'request': {u'node': {u'_arg': 0,
                                                                u'type': u'domnode'},
                                                      u'type': u'setOuterHTML',
                                                      u'value': {u'_arg': 1,
                                                                 u'type': u'primitive'}},
                                         u'response': {}},
                                        {u'name': u'removeNode',
                                         u'request': {u'node': {u'_arg': 0,
                                                                u'type': u'domnode'},
                                                      u'type': u'removeNode'},
                                         u'response': {u'nextSibling': {u'_retval': u'nullable:domnode'}}},
                                        {u'name': u'insertBefore',
                                         u'request': {u'node': {u'_arg': 0,
                                                                u'type': u'domnode'},
                                                      u'parent': {u'_arg': 1,
                                                                  u'type': u'domnode'},
                                                      u'sibling': {u'_arg': 2,
                                                                   u'type': u'nullable:domnode'},
                                                      u'type': u'insertBefore'},
                                         u'response': {}},
                                        {u'name': u'getMutations',
                                         u'request': {u'cleanup': {u'_option': 0,
                                                                   u'type': u'primitive'},
                                                      u'type': u'getMutations'},
                                         u'response': {u'mutations': {u'_retval': u'array:dommutation'}}}],
                           u'typeName': u'domwalker'},
            u'gl-program': {u'category': u'actor',
                            u'methods': [{u'name': u'getVertexShader',
                                          u'request': {u'type': u'getVertexShader'},
                                          u'response': {u'shader': {u'_retval': u'gl-shader'}}},
                                         {u'name': u'getFragmentShader',
                                          u'request': {u'type': u'getFragmentShader'},
                                          u'response': {u'shader': {u'_retval': u'gl-shader'}}},
                                         {u'name': u'highlight',
                                          u'oneway': True,
                                          u'request': {u'tint': {u'_arg': 0,
                                                                 u'type': u'array:number'},
                                                       u'type': u'highlight'},
                                          u'response': {}},
                                         {u'name': u'unhighlight',
                                          u'oneway': True,
                                          u'request': {u'type': u'unhighlight'},
                                          u'response': {}},
                                         {u'name': u'blackbox',
                                          u'oneway': True,
                                          u'request': {u'type': u'blackbox'},
                                          u'response': {}},
                                         {u'name': u'unblackbox',
                                          u'oneway': True,
                                          u'request': {u'type': u'unblackbox'},
                                          u'response': {}}],
                            u'typeName': u'gl-program'},
            u'gl-shader': {u'category': u'actor',
                           u'methods': [{u'name': u'getText',
                                         u'request': {u'type': u'getText'},
                                         u'response': {u'text': {u'_retval': u'string'}}},
                                        {u'name': u'compile',
                                         u'request': {u'text': {u'_arg': 0,
                                                                u'type': u'string'},
                                                      u'type': u'compile'},
                                         u'response': {u'error': {u'_retval': u'nullable:json'}}}],
                           u'typeName': u'gl-shader'},
            u'highlighter': {u'category': u'actor',
                             u'methods': [{u'name': u'showBoxModel',
                                           u'request': {u'node': {u'_arg': 0,
                                                                  u'type': u'domnode'},
                                                        u'scrollIntoView': {u'_option': 1,
                                                                            u'type': u'primitive'},
                                                        u'type': u'showBoxModel'},
                                           u'response': {}},
                                          {u'name': u'hideBoxModel',
                                           u'request': {u'type': u'hideBoxModel'},
                                           u'response': {}},
                                          {u'name': u'pick',
                                           u'request': {u'type': u'pick'},
                                           u'response': {}},
                                          {u'name': u'cancelPick',
                                           u'request': {u'type': u'cancelPick'},
                                           u'response': {}}],
                             u'typeName': u'highlighter'},
            u'imageData': {u'category': u'dict',
                           u'specializations': {u'data': u'nullable:longstring',
                                                u'size': u'json'},
                           u'typeName': u'imageData'},
            u'inspector': {u'category': u'actor',
                           u'methods': [{u'name': u'getWalker',
                                         u'request': {u'type': u'getWalker'},
                                         u'response': {u'walker': {u'_retval': u'domwalker'}}},
                                        {u'name': u'getPageStyle',
                                         u'request': {u'type': u'getPageStyle'},
                                         u'response': {u'pageStyle': {u'_retval': u'pagestyle'}}},
                                        {u'name': u'getHighlighter',
                                         u'request': {u'type': u'getHighlighter'},
                                         u'response': {u'highligter': {u'_retval': u'highlighter'}}}],
                           u'typeName': u'inspector'},
            u'longstractor': {u'category': u'actor',
                              u'methods': [{u'name': u'substring',
                                            u'request': {u'end': {u'_arg': 1,
                                                                  u'type': u'primitive'},
                                                         u'start': {u'_arg': 0,
                                                                    u'type': u'primitive'},
                                                         u'type': u'substring'},
                                            u'response': {u'substring': {u'_retval': u'primitive'}}},
                                           {u'name': u'release',
                                            u'release': True,
                                            u'request': {u'type': u'release'},
                                            u'response': {}}],
                              u'typeName': u'longstractor'},
            u'matchedselector': {u'category': u'dict',
                                 u'specializations': {u'rule': u'domstylerule#actorid',
                                                      u'selector': u'string',
                                                      u'status': u'number',
                                                      u'value': u'string'},
                                 u'typeName': u'matchedselector'},
            u'matchedselectorresponse': {u'category': u'dict',
                                         u'specializations': {u'matched': u'array:matchedselector',
                                                              u'rules': u'array:domstylerule',
                                                              u'sheets': u'array:stylesheet'},
                                         u'typeName': u'matchedselectorresponse'},
            u'memory': {u'category': u'actor',
                        u'methods': [{u'name': u'measure',
                                      u'request': {u'type': u'measure'},
                                      u'response': {u'_retval': u'json'}}],
                        u'typeName': u'memory'},
            u'old-stylesheet': {u'category': u'actor',
                                u'methods': [{u'name': u'toggleDisabled',
                                              u'request': {u'type': u'toggleDisabled'},
                                              u'response': {u'disabled': {u'_retval': u'boolean'}}},
                                             {u'name': u'fetchSource',
                                              u'request': {u'type': u'fetchSource'},
                                              u'response': {}},
                                             {u'name': u'update',
                                              u'request': {u'text': {u'_arg': 0,
                                                                     u'type': u'string'},
                                                           u'transition': {u'_arg': 1,
                                                                           u'type': u'boolean'},
                                                           u'type': u'update'},
                                              u'response': {}}],
                                u'typeName': u'old-stylesheet'},
            u'originallocationresponse': {u'category': u'dict',
                                          u'specializations': {u'column': u'number',
                                                               u'line': u'number',
                                                               u'source': u'string'},
                                          u'typeName': u'originallocationresponse'},
            u'originalsource': {u'category': u'actor',
                                u'methods': [{u'name': u'getText',
                                              u'request': {u'type': u'getText'},
                                              u'response': {u'text': {u'_retval': u'longstring'}}}],
                                u'typeName': u'originalsource'},
            u'pagestyle': {u'category': u'actor',
                           u'methods': [{u'name': u'getComputed',
                                         u'request': {u'filter': {u'_option': 1,
                                                                  u'type': u'string'},
                                                      u'markMatched': {u'_option': 1,
                                                                       u'type': u'boolean'},
                                                      u'node': {u'_arg': 0,
                                                                u'type': u'domnode'},
                                                      u'onlyMatched': {u'_option': 1,
                                                                       u'type': u'boolean'},
                                                      u'type': u'getComputed'},
                                         u'response': {u'computed': {u'_retval': u'json'}}},
                                        {u'name': u'getMatchedSelectors',
                                         u'request': {u'filter': {u'_option': 2,
                                                                  u'type': u'string'},
                                                      u'node': {u'_arg': 0,
                                                                u'type': u'domnode'},
                                                      u'property': {u'_arg': 1,
                                                                    u'type': u'string'},
                                                      u'type': u'getMatchedSelectors'},
                                         u'response': {u'_retval': u'matchedselectorresponse'}},
                                        {u'name': u'getApplied',
                                         u'request': {u'filter': {u'_option': 1,
                                                                  u'type': u'string'},
                                                      u'inherited': {u'_option': 1,
                                                                     u'type': u'boolean'},
                                                      u'matchedSelectors': {u'_option': 1,
                                                                            u'type': u'boolean'},
                                                      u'node': {u'_arg': 0,
                                                                u'type': u'domnode'},
                                                      u'type': u'getApplied'},
                                         u'response': {u'_retval': u'appliedStylesReturn'}},
                                        {u'name': u'getLayout',
                                         u'request': {u'autoMargins': {u'_option': 1,
                                                                       u'type': u'boolean'},
                                                      u'node': {u'_arg': 0,
                                                                u'type': u'domnode'},
                                                      u'type': u'getLayout'},
                                         u'response': {u'_retval': u'json'}}],
                           u'typeName': u'pagestyle'},
            u'styleeditor': {u'category': u'actor',
                             u'methods': [{u'name': u'newDocument',
                                           u'request': {u'type': u'newDocument'},
                                           u'response': {}},
                                          {u'name': u'newStyleSheet',
                                           u'request': {u'text': {u'_arg': 0,
                                                                  u'type': u'string'},
                                                        u'type': u'newStyleSheet'},
                                           u'response': {u'styleSheet': {u'_retval': u'old-stylesheet'}}}],
                             u'typeName': u'styleeditor'},
            u'stylesheet': {u'category': u'actor',
                            u'methods': [{u'name': u'toggleDisabled',
                                          u'request': {u'type': u'toggleDisabled'},
                                          u'response': {u'disabled': {u'_retval': u'boolean'}}},
                                         {u'name': u'getText',
                                          u'request': {u'type': u'getText'},
                                          u'response': {u'text': {u'_retval': u'longstring'}}},
                                         {u'name': u'getOriginalSources',
                                          u'request': {u'type': u'getOriginalSources'},
                                          u'response': {u'originalSources': {u'_retval': u'nullable:array:originalsource'}}},
                                         {u'name': u'getOriginalLocation',
                                          u'request': {u'column': {u'_arg': 1,
                                                                   u'type': u'number'},
                                                       u'line': {u'_arg': 0,
                                                                 u'type': u'number'},
                                                       u'type': u'getOriginalLocation'},
                                          u'response': {u'_retval': u'originallocationresponse'}},
                                         {u'name': u'update',
                                          u'request': {u'text': {u'_arg': 0,
                                                                 u'type': u'string'},
                                                       u'transition': {u'_arg': 1,
                                                                       u'type': u'boolean'},
                                                       u'type': u'update'},
                                          u'response': {}}],
                            u'typeName': u'stylesheet'},
            u'stylesheets': {u'category': u'actor',
                             u'methods': [{u'name': u'getStyleSheets',
                                           u'request': {u'type': u'getStyleSheets'},
                                           u'response': {u'styleSheets': {u'_retval': u'array:stylesheet'}}},
                                          {u'name': u'addStyleSheet',
                                           u'request': {u'text': {u'_arg': 0,
                                                                  u'type': u'string'},
                                                        u'type': u'addStyleSheet'},
                                           u'response': {u'styleSheet': {u'_retval': u'stylesheet'}}}],
                             u'typeName': u'stylesheets'},
            u'webgl': {u'category': u'actor',
                       u'methods': [{u'name': u'setup',
                                     u'oneway': True,
                                     u'request': {u'reload': {u'_option': 0,
                                                              u'type': u'boolean'},
                                                  u'type': u'setup'},
                                     u'response': {}},
                                    {u'name': u'finalize',
                                     u'oneway': True,
                                     u'request': {u'type': u'finalize'},
                                     u'response': {}},
                                    {u'name': u'getPrograms',
                                     u'request': {u'type': u'getPrograms'},
                                     u'response': {u'programs': {u'_retval': u'array:gl-program'}}}],
                       u'typeName': u'webgl'}}}
